In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import svm 
from sklearn import metrics
from sklearn.tree import DecisionTreeRegressor

In [2]:
data = pd.read_csv('UNFCCC_v24.csv', encoding= 'unicode_escape')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_24964\3978362536.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('UNFCCC_v24.csv', encoding= 'unicode_escape')

In [3]:
data.head(7)

,Country_code,Country,Format_name,Pollutant_name,Sector_code,Sector_name,Parent_sector_code,Unit,Year,emissions,Notation,PublicationDate,DataSource
0,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.2,2.E.2 - TFT Flat Panel Display,2.E,Gg CO2 equivalent,2008,NaN,NO,20210616,EEA
1,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.3,2.E.3 - Photovoltaics,2.E,Gg CO2 equivalent,1992,NaN,NO,20210616,EEA
2,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.3,2.E.3 - Photovoltaics,2.E,Gg CO2 equivalent,2010,NaN,NO,20210616,EEA
3,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.3,2.E.3 - Photovoltaics,2.E,Gg CO2 equivalent,2017,NaN,NO,20210616,EEA
4,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.5,2.E.5 - Other electronics industry,2.E,Gg CO2 equivalent,1993,NaN,NO,20210616,EEA
5,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.5,2.E.5 - Other electronics industry,2.E,Gg CO2 equivalent,2001,NaN,NO,20210616,EEA
6,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b,1.A.3.b - Road Transportation,1.A.3,Gg,2009,0.10775,NaN,20210616,EEA

In [4]:
#removing the unnamed Column
data.drop(columns='Notation' , axis = 1, inplace=True)
data.head(7)

,Country_code,Country,Format_name,Pollutant_name,Sector_code,Sector_name,Parent_sector_code,Unit,Year,emissions,PublicationDate,DataSource
0,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.2,2.E.2 - TFT Flat Panel Display,2.E,Gg CO2 equivalent,2008,NaN,20210616,EEA
1,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.3,2.E.3 - Photovoltaics,2.E,Gg CO2 equivalent,1992,NaN,20210616,EEA
2,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.3,2.E.3 - Photovoltaics,2.E,Gg CO2 equivalent,2010,NaN,20210616,EEA
3,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.3,2.E.3 - Photovoltaics,2.E,Gg CO2 equivalent,2017,NaN,20210616,EEA
4,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.5,2.E.5 - Other electronics industry,2.E,Gg CO2 equivalent,1993,NaN,20210616,EEA
5,NL,Netherlands,IPCC Common Reporting Format,SF6 - (CO2 equivalent),2.E.5,2.E.5 - Other electronics industry,2.E,Gg CO2 equivalent,2001,NaN,20210616,EEA
6,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b,1.A.3.b - Road Transportation,1.A.3,Gg,2009,0.10775,20210616,EEA

In [5]:
data.shape

(686348, 12)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 686348 entries, 0 to 686347
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Country_code        686348 non-null  object
 1   Country             686348 non-null  object
 2   Format_name         686348 non-null  object
 3   Pollutant_name      686348 non-null  object
 4   Sector_code         686348 non-null  object
 5   Sector_name         686348 non-null  object
 6   Parent_sector_code  628766 non-null  object
 7   Unit                686348 non-null  object
 8   Year                686348 non-null  object
 9   emissions           426498 non-null  float64
 10  PublicationDate     686348 non-null  int64
 11  DataSource          686348 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 62.8+ MB

In [7]:
# checking for missing values
data.isnull().sum()

Country_code               0
Country                    0
Format_name                0
Pollutant_name             0
Sector_code                0
Sector_name                0
Parent_sector_code     57582
Unit                       0
Year                       0
emissions             259850
PublicationDate            0
DataSource                 0
dtype: int64

In [8]:
data.describe()

          emissions  PublicationDate
count  4.264980e+05         686348.0
mean   2.549875e+04       20210616.0
std    2.517595e+05              0.0
min   -4.673036e+05       20210616.0
25%    4.483300e-01       20210616.0
50%    4.070052e+01       20210616.0
75%    1.109751e+03       20210616.0
max    5.849394e+06       20210616.0

In [9]:
#droping the observations where there are missing values 
data.dropna(inplace=True)

In [10]:
data.shape

(380988, 12)

In [11]:
data.head(50)

,Country_code,Country,Format_name,Pollutant_name,Sector_code,Sector_name,Parent_sector_code,Unit,Year,emissions,PublicationDate,DataSource
6,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b,1.A.3.b - Road Transportation,1.A.3,Gg,2009,0.10775,20210616,EEA
7,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b.i,1.A.3.b.i - Cars,1.A.3.b,Gg,2009,0.08124,20210616,EEA
8,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b.i,1.A.3.b.i - Cars,1.A.3.b,Gg,2012,0.07069,20210616,EEA
9,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b.i,1.A.3.b.i - Cars,1.A.3.b,Gg,2019,0.10371,20210616,EEA
10,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b.iii,1.A.3.b.iii - Heavy duty trucks and buses,1.A.3.b,Gg,2008,0.03074,20210616,EEA
11,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b.iii,1.A.3.b.iii - Heavy duty trucks and buses,1.A.3.b,Gg,2011,0.02634,20210616,EEA
12,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b.iv,1.A.3.b.iv - Motorcycles,1.A.3.b,Gg,1997,0.00029,20210616,EEA
13,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.b.iv,1.A.3.b.iv - Motorcycles,1.A.3.b,Gg,2001,0.00019,20210616,EEA
20,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.c,1.A.3.c - Railways,1.A.3,Gg,1996,0.09867,20210616,EEA
21,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.c,1.A.3.c - Railways,1.A.3,Gg,2013,0.06277,20210616,EEA
22,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.c,1.A.3.c - Railways,1.A.3,Gg,2017,0.06477,20210616,EEA
23,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.d,1.A.3.d - Domestic Navigation,1.A.3,Gg,1990,0.00042,20210616,EEA
24,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.d,1.A.3.d - Domestic Navigation,1.A.3,Gg,2003,0.00036,20210616,EEA
25,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.d,1.A.3.d - Domestic Navigation,1.A.3,Gg,2007,0.00049,20210616,EEA
26,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.d,1.A.3.d - Domestic Navigation,1.A.3,Gg,2012,0.00041,20210616,EEA
27,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.d,1.A.3.d - Domestic Navigation,1.A.3,Gg,2014,0.00040,20210616,EEA
28,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.3.e,1.A.3.e - Other Transportation,1.A.3,Gg,2006,0.00104,20210616,EEA
29,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4,1.A.4 - Other Sectors,1.AA,Gg,1998,0.18760,20210616,EEA
30,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4,1.A.4 - Other Sectors,1.AA,Gg,2008,0.15614,20210616,EEA
31,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4,1.A.4 - Other Sectors,1.AA,Gg,2010,0.15409,20210616,EEA
32,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4.a,1.A.4.a - Commercial/Institutional,1.A.4,Gg,1995,0.09587,20210616,EEA
33,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4.b,1.A.4.b - Residential,1.A.4,Gg,1993,0.07979,20210616,EEA
34,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4.b,1.A.4.b - Residential,1.A.4,Gg,1996,0.07615,20210616,EEA
35,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4.b,1.A.4.b - Residential,1.A.4,Gg,1997,0.07777,20210616,EEA
36,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4.b,1.A.4.b - Residential,1.A.4,Gg,2013,0.09547,20210616,EEA
37,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4.c,1.A.4.c - Agriculture/Forestry/Fishing,1.A.4,Gg,2001,0.03777,20210616,EEA
38,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.4.c,1.A.4.c - Agriculture/Forestry/Fishing,1.A.4,Gg,2004,0.03990,20210616,EEA
39,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.5,1.A.5 - Other Other Sectors,1.AA,Gg,1991,0.00001,20210616,EEA
40,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.5,1.A.5 - Other Other Sectors,1.AA,Gg,1993,0.00002,20210616,EEA
41,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.5.b,1.A.5.b - Mobile,1.A.5,Gg,2011,0.00035,20210616,EEA
42,LT,Lithuania,IPCC Common Reporting Format,N2O,1.A.5.b,1.A.5.b - Mobile,1.A.5,Gg,2013,0.00048,20210616,EEA
43,LT,Lithuania,IPCC Common Reporting Format,N2O,1.AA,1.AA - Fuel Combustion - Sectoral approach,1,Gg,1995,0.60360,20210616,EEA
44,LT,Lithuania,IPCC Common Reporting Format,N2O,1.AA,1.AA - Fuel Combustion - Sectoral approach,1,Gg,1999,0.45804,20210616,EEA
45,LT,Lithuania,IPCC Common Reporting Format,N2O,1.AA,1.AA - Fuel Combustion - Sectoral approach,1,Gg,2008,0.51773,20210616,EEA
46,LT,Lithuania,IPCC Common Reporting Format,N2O,1.AA,1.AA - Fuel Combustion - Sectoral approach,1,Gg,2019,0.55775,20210616,EEA
47,LT,Lithuania,IPCC Common Reporting Format,N2O,1.B.2,1.B.2 - Oil and Natural Gas and Other Emission...,1.B,Gg,1991,0.00003,20210616,EEA
48,LT,Lithuania,IPCC Common Reporting Format,N2O,1.B.2,1.B.2 - Oil and Natural Gas and Other Emission...,1.B,Gg,1992,0.00005,20210616,EEA
49,LT,Lithuania,IPCC Common Reporting Format,N2O,1.B.2,1.B.2 - Oil and Natural Gas and Other Emission...,1.B,Gg,2000,0.00026,20210616,EEA
50,LT,Lithuania,IPCC Common Reporting Format,N2O,1.B.2,1.B.2 - Oil and Natural Gas and Other Emission...,1.B,Gg,2003,0.00032,20210616,EEA
51,LT,Lithuania,IPCC Common Reporting Format,N2O,1.D.1,1.D.1 - International Bunkers,1.D,Gg,2008,0.01380,20210616,EEA
52,LT,Lithuania,IPCC Common Reporting Format,N2O,1.D.1.a,1.D.1.a - International Aviation,1.D.1,Gg,2000,0.00194,20210616,EEA
53,LT,Lithuania,IPCC Common Reporting Format,N2O,1.D.1.a,1.D.1.a - International Aviation,1.D.1,Gg,2009,0.00304,20210616,EEA
94,LT,Lithuania,IPCC Common Reporting Format,CH4,2.B.8,2.B.8 - Petrochemical and Carbon Black Production,2.B,Gg,1995,0.08963,20210616,EEA
95,LT,Lithuania,IPCC Common Reporting Format,CH4,2.B.8,2.B.8 - Petrochemical and Carbon Black Production,2.B,Gg,1997,0.05405,20210616,EEA
96,LT,Lithuania,IPCC Common Reporting Format,CH4,2.B.8,2.B.8 - Petrochemical and Carbon Black Production,2.B,Gg,2002,0.06789,20210616,EEA
97,LT,Lithuania,IPCC Common Reporting Format,CH4,2.B.8,2.B.8 - Petrochemical and Carbon Black Production,2.B,Gg,2006,0.10987,20210616,EEA
112,LT,Lithuania,IPCC Common Reporting Format,CH4,3,3 - Agriculture,Sectors/Totals_incl_incl,Gg,2012,76.16935,20210616,EEA
113,LT,Lithuania,IPCC Common Reporting Format,CH4,3.1,3.1 - Livestock,3,Gg,1990,198.27301,20210616,EEA
114,LT,Lithuania,IPCC Common Reporting Format,CH4,3.1,3.1 - Livestock,3,Gg,2000,80.25148,20210616,EEA
115,LT,Lithuania,IPCC Common Reporting Format,CH4,3.1,3.1 - Livestock,3,Gg,2008,80.30064,20210616,EEA

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Country_code']=le.fit_transform(data['Country_code'])
data['Country']=le.fit_transform(data['Country'])
data['Sector_code']=le.fit_transform(data['Sector_code'])
data['Sector_name']=le.fit_transform(data['Sector_name'])
data['Parent_sector_code']=le.fit_transform(data['Parent_sector_code'])
data['Pollutant_name']=le.fit_transform(data['Pollutant_name'])
data['Unit']=le.fit_transform(data['Unit'])
data['DataSource']=le.fit_transform(data['DataSource'])
data['Format_name']=le.fit_transform(data['Format_name'])
data.replace({'PublicationDate':{20210616:0}},inplace=True)

In [13]:
data.head()

,Country_code,Country,Format_name,Pollutant_name,Sector_code,Sector_name,Parent_sector_code,Unit,Year,emissions,PublicationDate,DataSource
6,21,20,0,4,16,16,3,0,2009,0.10775,0,0
7,21,20,0,4,17,17,4,0,2009,0.08124,0,0
8,21,20,0,4,17,17,4,0,2012,0.07069,0,0
9,21,20,0,4,17,17,4,0,2019,0.10371,0,0
10,21,20,0,4,19,19,4,0,2008,0.03074,0,0

In [14]:
data.isnull().sum()

Country_code          0
Country               0
Format_name           0
Pollutant_name        0
Sector_code           0
Sector_name           0
Parent_sector_code    0
Unit                  0
Year                  0
emissions             0
PublicationDate       0
DataSource            0
dtype: int64

In [15]:
X =data.drop(['emissions'],axis=1) 
Y =data['emissions']

In [16]:
X = X.apply(pd.to_numeric, errors='coerce')
Y = Y.apply(pd.to_numeric, errors='coerce')

In [17]:
X.fillna(0, inplace=True)
Y.fillna(0, inplace=True)

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2) #80% will be trained data and 20% will be testing data

In [19]:
print(X.shape, X_train.shape, X_test.shape)
print(Y.shape, Y_train.shape, Y_test.shape)

(380988, 11) (304790, 11) (76198, 11)
(380988,) (304790,) (76198,)

In [20]:
#loading lineair regression model
lin_reg_model = LinearRegression()

In [21]:
lin_reg_model.fit(X_train, Y_train)

LinearRegression()

In [22]:
#Prediction on Training data
training_data_prediction = lin_reg_model.predict(X_train)

In [23]:
# R squared Error
error_score = metrics.r2_score(Y_train, training_data_prediction) #should be as low as possible
print('R squared Error:' , error_score)

R squared Error: 0.020392757521696336

In [24]:
#from sklearn.svm import SVR
#svr = SVR()
#svr.fit(X_train, Y_train)

In [25]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()

In [26]:
model.fit(X_train, Y_train)

DecisionTreeRegressor()

In [27]:
predictions = model.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_error
model.score(X_test, predictions)

1.0

In [29]:
features = np.array([[21, 20,0, 4,16,16,3,0,2009,0,0]])
print(model.predict(features))

[0.10775]

C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [30]:
features = np.array([[25, 23,0, 6,170,170,11,1,2019,0,0]])
print(model.predict(features))

[3.77667]

C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [31]:
features = np.array([[25, 23,0, 7,42,42,38,1,1998,0,0]])
print(model.predict(features))

[266.2128]

C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [32]:
features = np.array([[23, 21,0, 6,120,126,3,0,2009,0,0]]) #aléatoire
print(model.predict(features))

[0.00211]

C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

=> Les prédictions ne sont pas précises